# Generated by Django 3.1.4 on 2024-07-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidade',
            field=models.CharField(max_length=20),
        ),
    ]
