# Generated by Django 3.1.4 on 2024-07-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_itemestoque_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemestoque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
