# Generated by Django 5.0.6 on 2024-07-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_itemestoque_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemEstoque',
            new_name='Item',
        ),
    ]
