# Generated by Django 3.1.4 on 2024-07-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='Agendamento',
        ),
    ]
