# Generated by Django 3.1.4 on 2024-07-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_auto_20240630_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='profissional',
            new_name='cliente',
        ),
    ]
