# Generated by Django 3.1.4 on 2024-07-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_auto_20240702_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('technician', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
    ]
