# Generated by Django 5.0.6 on 2024-10-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasareceber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contasareceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ContaReceber',
        ),
    ]
