# Generated by Django 5.0.6 on 2024-10-28 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='data',
            new_name='validade',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='endereco',
            field=models.CharField(default=4899618676, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamento',
            name='materiais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='prazo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
