# Generated by Django 5.0.6 on 2024-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_rename_data_orcamento_validade_orcamento_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='endereco',
            field=models.TextField(),
        ),
    ]
